/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package iudigital.daoapp;



import iudigital.daoapp.conexion.Conectar;
import iudigital.daoapp.controller.FuncionarioController;

import iudigital.daoapp.dominio.Ciudad;
import iudigital.daoapp.dominio.EstadoCivil;
import iudigital.daoapp.dominio.Funcionario;

import iudigital.daoapp.dominio.Sexo;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author SOPORTE
 */
public class ViewFuncionario extends javax.swing.JFrame{
    DefaultTableModel modelo;
    
    /**
     * Creates new form frmFuncionarios
     * @throws java.sql.SQLException
     */
    public ViewFuncionario() throws SQLException {
        initComponents();    
	   	
        setSize(1150, 550);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
       
        String[] titulos = {"Cedula", "Nombres", "Apellidos", "Celular", "Estado", "Sexo", "Fecha", "Direccion", "Ciudad"};
        modelo = new DefaultTableModel(null, titulos);
        tblfuncionarios.setModel(modelo);
        
        mostrarDatosTabla();
        llenarEstadoCivil();
        llenarSexo();
        llenarCiudad();
        limpiar();
        txtidestadocivil.setVisible(false);
        txtidsexo.setVisible(false);
        txtidciudad.setVisible(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblfuncionarios = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnactualizar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btnborrar = new javax.swing.JButton();
        txtidfuncionario = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        txtcelular = new javax.swing.JTextField();
        txtidsexo = new javax.swing.JTextField();
        txtidestadocivil = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        txtfechanacimiento = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidciudad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbxestadocivil = new javax.swing.JComboBox<>();
        btncancelar = new javax.swing.JButton();
        cbxsexo = new javax.swing.JComboBox<>();
        cbxciudad = new javax.swing.JComboBox<>();

        setTitle("INFORMACIÓN DE FUNCIONARIO");
        setUndecorated(true);

        tblfuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblfuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblfuncionariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblfuncionarios);

        btnagregar.setText("Agregar");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnactualizar.setText("Actualizar");
        btnactualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactualizarActionPerformed(evt);
            }
        });

        btnsalir.setText("Salir");
        btnsalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnsalirMousePressed(evt);
            }
        });

        btnborrar.setText("Borrar");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });

        jLabel1.setText("Identificación");

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Celular");

        jLabel5.setText("Sexo");

        jLabel6.setText("Estado Civil");

        jLabel7.setText("Dirección");

        jLabel8.setText("Fecha Nacimiento");

        jLabel9.setText("Ciudad");

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel10.setText("INFORMACIO DE FUNCIONARIO");

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(503, 503, 503)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtidestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtidsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(80, 80, 80)
                                        .addComponent(txtidciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(285, 285, 285)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(161, 161, 161)
                                        .addComponent(jLabel2)
                                        .addGap(370, 370, 370)
                                        .addComponent(jLabel3))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(160, 160, 160)
                                        .addComponent(jLabel7)
                                        .addGap(277, 277, 277)
                                        .addComponent(jLabel4)
                                        .addGap(152, 152, 152)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(57, 57, 57)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtapellidos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(cbxestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(jLabel1)
                                        .addGap(185, 185, 185)
                                        .addComponent(jLabel9)
                                        .addGap(152, 152, 152)
                                        .addComponent(jLabel6)
                                        .addGap(208, 208, 208)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtidfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(cbxciudad, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(429, 429, 429)
                                .addComponent(btnagregar)
                                .addGap(28, 28, 28)
                                .addComponent(btnactualizar)
                                .addGap(37, 37, 37)
                                .addComponent(btnborrar)
                                .addGap(39, 39, 39)
                                .addComponent(btncancelar)
                                .addGap(39, 39, 39)
                                .addComponent(btnsalir)))
                        .addGap(0, 442, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtidciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxestadocivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtidfuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxsexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtnombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtapellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfechanacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar)
                    .addComponent(btnactualizar)
                    .addComponent(btnsalir)
                    .addComponent(btnborrar)
                    .addComponent(btncancelar))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        jLabel10.getAccessibleContext().setAccessibleName("lbltitulo");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        try {
            agregarFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnagregarActionPerformed
    
    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        try {
            borrarFuncionario();
        } catch (SQLException ex) {
            Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnactualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactualizarActionPerformed
        try {
            actualizarFuncionario() ;
        } catch (SQLException ex) {
            Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnactualizarActionPerformed
  
    private void tblfuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblfuncionariosMouseClicked
        // TODO add your handling code here:
        
        try {
            if (evt.getClickCount()==1){
            
                JTable receptor = (JTable)evt.getSource();
            
                txtidfuncionario.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),0).toString());
                txtnombres.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),1).toString());
                txtapellidos.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),2).toString());
                txtcelular.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),3).toString());
                txtidestadocivil.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),4).toString());
                txtidsexo.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),5).toString());
                txtfechanacimiento.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),6).toString());
                txtdireccion.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),7).toString());
                txtidciudad.setText(receptor.getModel().getValueAt( receptor.getSelectedRow(),8).toString());
                
                cbxestadocivil.setSelectedIndex(Integer.parseInt(txtidestadocivil.getText()));
                cbxsexo.setSelectedIndex(Integer.parseInt(txtidsexo.getText()));
                cbxciudad.setSelectedIndex(Integer.parseInt(txtidciudad.getText()));
                
                btnborrar.setEnabled(true);
                btnactualizar.setEnabled(true);
                txtidfuncionario.setEnabled(false);

               
               // cbxsexo.setSelectedIndex(Integer.parseInt(txtidsexo.getText()));
        }   
        } catch (NumberFormatException e) {
            System.out.println("Error : " + e);
        } catch (Exception e){
                System.out.println("" + e);
        } 
    }//GEN-LAST:event_tblfuncionariosMouseClicked

    private void btnsalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsalirMousePressed
        // TODO add your handling code here:
        if (evt.getClickCount()==1)
        {    
            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro?", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp==0) 
                System.exit(0);
        }    
    }//GEN-LAST:event_btnsalirMousePressed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_btncancelarActionPerformed


    public ArrayList<Sexo> getSexo() throws SQLException{
        
        Connection connection = null;
        PreparedStatement pstm = null;
 
        try {
            connection = Conectar.getConnection();
            ArrayList<Sexo> listasexo = new ArrayList<>();

            String strSentenciaSQL = "SELECT * FROM [RRHH-IUDIGITAL].dbo.sexo";
            pstm = connection.prepareStatement(strSentenciaSQL);
            ResultSet resultado = pstm.executeQuery();

            while (resultado.next()){

                Sexo sex = new Sexo();

                sex.setIdsexo(resultado.getInt("idsexo"));
                sex.setSexo(resultado.getString("sexo"));
                listasexo.add(sex);
            }
            return listasexo;

        } catch (SQLException e) {
            System.out.println("Error " + e);
            return null;
        }finally{
          int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
          System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
          int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
          System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
          connection.close();
          System.out.println("Conexion BD cerrada en Recuperar Sexo");
        }
    }
    
    private void llenarSexo(){ 
        try {
            ArrayList<Sexo> listasexo;
            cbxsexo.removeAllItems();
            listasexo = getSexo();
      
            for (int i=0; i<listasexo.size(); i++){

                cbxsexo.addItem(new Sexo(listasexo.get(i).getIdsexo(),listasexo.get(i).getSexo()));
            }
            
        } catch (SQLException e) {
            System.out.println("Error :" + e );
        }
   
    }    
        
    public ArrayList<EstadoCivil> getEstadoCivil() throws SQLException{
        
        Connection connection = null;
        PreparedStatement pstm = null;
        
        try {
            connection = Conectar.getConnection();            
            ArrayList<EstadoCivil> listaestadocivil = new ArrayList<>();

            String strSentenciaSQL = "SELECT * FROM [RRHH-IUDIGITAL].dbo.estadocivil";
            pstm = connection.prepareStatement(strSentenciaSQL);
            ResultSet resultado = pstm.executeQuery();
        
            while (resultado.next()){
                
                EstadoCivil EC = new EstadoCivil();
                
                EC.setIdestadocivil(resultado.getInt("idestadocivil"));
                EC.setEstadocivil(resultado.getString("estadocivil"));
                listaestadocivil.add(EC);
            }
            return listaestadocivil;
            
        } catch (SQLException e) {
            System.out.println("Error " + e);
            return null;
        }finally{
          int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
          System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
          int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
          System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
          connection.close();
          System.out.println("Conexion a BD Cerrada en recuperar Estado Civil"); 

        }
       
    }
    
    private void llenarEstadoCivil(){ 
        try {
            ArrayList<EstadoCivil> listaestadocivil;
        
            listaestadocivil = getEstadoCivil();
            cbxestadocivil.removeAllItems();

            for (int i=0; i<listaestadocivil.size(); i++){

                cbxestadocivil.addItem(new EstadoCivil(listaestadocivil.get(i).getIdestadocivil(),listaestadocivil.get(i).getEstadocivil() ));
            }
            
        } catch (SQLException e) {
            System.out.println("Error :" + e);
        }
   
    }    
   
    public ArrayList<Ciudad> getCiudad() throws SQLException{
        
        Connection connection = null;
        PreparedStatement pstm = null;
      
        try {
            connection = Conectar.getConnection();            
            ArrayList<Ciudad> listaciudad = new ArrayList<>();

            String strSentenciaSQL = "SELECT * FROM [RRHH-IUDIGITAL].dbo.cidudad";
            pstm = connection.prepareStatement(strSentenciaSQL);
            ResultSet resultado = pstm.executeQuery();
        
            while (resultado.next()){
                
                Ciudad Ciu = new Ciudad();
                
                Ciu.setIdciudad(resultado.getInt("idciudad"));
                Ciu.setCiudad(resultado.getString("ciudad"));
                listaciudad.add(Ciu);
            }
            return listaciudad;
            
        } catch (SQLException e) {
            System.out.println("Error " + e);
            return null;
        }finally{
          int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
          System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
          int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
          System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
          connection.close();
          System.out.println("Conexion a BD Cerrada en recuperar Ciudad"); 
        }
    }
    
    private void llenarCiudad(){ 
        try {
            ArrayList<Ciudad> listaciudad;

            listaciudad = getCiudad();
            cbxciudad.removeAllItems();

            for (int i=0; i<listaciudad.size(); i++){

                cbxciudad.addItem(new Ciudad(listaciudad.get(i).getIdciudad(),listaciudad.get(i).getCiudad() ));
            }

        } catch (Exception e) {
            System.out.println("Error :" + e);
        }
   
    }       
             
    private void limpiar(){
        
        String texto = "";
        txtidfuncionario.setText(texto);
        txtnombres.setText(texto);
        txtapellidos.setText(texto);
        txtcelular.setText(texto);
        txtidestadocivil.setText(texto);
        cbxestadocivil.setSelectedIndex(0);
        cbxsexo.setSelectedIndex(0);
        cbxciudad.setSelectedIndex(0);
        txtidsexo.setText(texto);
        txtfechanacimiento.setText(texto);
        txtdireccion.setText(texto);
        txtidciudad.setText(texto);        
        btnagregar.setEnabled(true);
        btnactualizar.setEnabled(false);
        btnborrar.setEnabled(false);
        btnsalir.setEnabled(true);
        txtidfuncionario.setEnabled(true);
        
 }
    
    public Funcionario recuperarFuncionario(){

        Funcionario objfuncionario = new Funcionario();

        objfuncionario.setIdfuncionario(txtidfuncionario.getText());
        objfuncionario.setNombres(txtnombres.getText());
        objfuncionario.setApellidos(txtapellidos.getText());
        objfuncionario.setCelular(txtcelular.getText());
        objfuncionario.setIdestadocivil(cbxestadocivil.getItemAt(cbxestadocivil.getSelectedIndex()).getIdestadocivil());
        objfuncionario.setIdsexo(cbxsexo.getItemAt(cbxsexo.getSelectedIndex()).getIdsexo());
        objfuncionario.setIdciudad(cbxciudad.getItemAt(cbxciudad.getSelectedIndex()).getIdciudad());
        objfuncionario.setFechanacimiento(txtfechanacimiento.getText());
        objfuncionario.setDireccion(txtdireccion.getText());

    return objfuncionario; 
        
    }    
        
    
    private void mostrarDatosTabla() throws SQLException{
        FuncionarioController funcionarioController = new FuncionarioController();
        List<Funcionario> listafuncionarios = new ArrayList<>();
        Connection connection = null;
        PreparedStatement pstm = null;
        connection = Conectar.getConnection();
        System.out.println("Conexión a la BD establecida en Mostrar datos ");
        
        try {
            while (modelo.getRowCount()>0){
                modelo.removeRow(0);
            }
            listafuncionarios = funcionarioController.obtenerFuncionarios();
            
            listafuncionarios.forEach( funcionario ->
            {
                Object[] objfuncionario = {funcionario.getIdfuncionario(), funcionario.getNombres(), funcionario.getApellidos(), funcionario.getCelular(),funcionario.getIdestadocivil(),funcionario.getIdsexo(), funcionario.getFechanacimiento(), funcionario.getDireccion(), funcionario.getIdciudad()};
                modelo.addRow(objfuncionario);
            });
        } catch (SQLException e) {
            System.out.println("Error " + e); 
        } finally{
          int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
          System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
          int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
          System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
          connection.close();
          System.out.println("Conexion a BD Cerrada en Mostrar datos en tabla"); 
        } 
    }
   
    public void agregarFuncionario() throws SQLException {                                            
                FuncionarioController funcionarioController = new FuncionarioController();                       
                Connection connection = null;
                connection = Conectar.getConnection();
                System.out.println("Conexión a la BD establecida en Agregar Funcionario ");
                try {
                    Funcionario funcionario = recuperarFuncionario();
                    funcionarioController.crearFuncionario(funcionario);
                    this.mostrarDatosTabla();
                    JOptionPane.showMessageDialog(null, "Funcionario agregado correctamente");
                } catch (HeadlessException e) {
                    System.out.println("Funcionario no fue Agregado " + e);
                } catch (NumberFormatException NF){
                    System.out.println("Campos incorrectos " + NF);
                } catch (SQLException ex) {
                    Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
                } finally{
                    int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
                    System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
                    int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
                    System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
                    connection.close();
                    System.out.println("Conexion a BD Cerrada en Agegar Funcionario");
                    this.limpiar();
                }
    }                                             

    public void borrarFuncionario() throws SQLException {
        FuncionarioController funcionarioController = new FuncionarioController();
        Connection connection = null;
        connection = Conectar.getConnection();
        System.out.println("Conexión a la BD establecida en Borrar Funcionario ");
        try {
            Funcionario objfuncionario = recuperarFuncionario();     
            String id = objfuncionario.getIdfuncionario();
            funcionarioController.eliminarFuncionario(id);
            this.mostrarDatosTabla();
            this.limpiar();
            JOptionPane.showMessageDialog(null, "Funcionario eliminado correctamente");           
        } catch (HeadlessException e) {
            System.out.println("Error al borar registro " + e);
        } catch (SQLException ex) {
            Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
            System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
            int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
            System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
            connection.close();
            System.out.println("Conexion a BD Cerrada en Borrar Funcionario");
        }
    }                                         

    public void actualizarFuncionario() throws SQLException {
        FuncionarioController funcionarioController = new FuncionarioController();
        Connection connection = null;
        connection = Conectar.getConnection();
        System.out.println("Conexión a la BD establecida en Actualizar ");
        try {
            Funcionario objfuncionario = recuperarFuncionario();
            String id = objfuncionario.getIdfuncionario();
            funcionarioController.actualizarFuncionario(id, objfuncionario);
            this.mostrarDatosTabla();
            JOptionPane.showMessageDialog(null, "Funcionario actualizado correctamente");
            this.limpiar();
        } catch (HeadlessException e) {
            System.out.println("Funcionario no fue Agregado " + e); 
        } catch (NumberFormatException NF){
            System.out.println("Campos incorrectos " + NF);
        } finally{
            int CLOSE_CURSORS_AT_COMMIT = ResultSet.CLOSE_CURSORS_AT_COMMIT;
            System.out.println("ResultSet cerrado " + CLOSE_CURSORS_AT_COMMIT); 
            int CLOSE_ALL_RESULTS = PreparedStatement.CLOSE_ALL_RESULTS;
            System.out.println("PreparedStatement cerrado " + CLOSE_ALL_RESULTS);
            connection.close();
            System.out.println("Conexion a BD Cerrada en Actualizar Funcionario");
        }      
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
           java.awt.EventQueue.invokeLater(() -> {
               try {
                   new ViewFuncionario().setVisible(true);
               } catch (SQLException ex) {
                   Logger.getLogger(ViewFuncionario.class.getName()).log(Level.SEVERE, null, ex);
               }
           });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnactualizar;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnborrar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JComboBox<Ciudad> cbxciudad;
    private javax.swing.JComboBox<EstadoCivil> cbxestadocivil;
    private javax.swing.JComboBox<Sexo> cbxsexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblfuncionarios;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcelular;
    private javax.swing.JTextField txtdireccion;
    private javax.swing.JTextField txtfechanacimiento;
    private javax.swing.JTextField txtidciudad;
    private javax.swing.JTextField txtidestadocivil;
    private javax.swing.JTextField txtidfuncionario;
    private javax.swing.JTextField txtidsexo;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
